version: "3.9"
services:
  worker:
    build: .
    environment:
      HU_STRING_SESSION: $HU_STRING_SESSION
      REDIS_PASSWORD: $REDIS_PASSWORD
      SESSION: $SESSION
      UPSTREAM_REPO: $UPSTREAM_REPO
      API_ID: $API_ID
      API_HASH: $API_HASH
      LOG_CHANNEL_ID: $LOG_CHANNEL_ID
      LOG_CHANNEL_ID: $LOG_CHANNEL_ID
      BOT_MEDIA: $BOT_MEDIA
      ALIVE_MEDIA: $ALIVE_MEDIA
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      MONGO_URI: $MONGO_URI  # defaults to None
      BOT_TOKEN: $BOT_TOKEN # Not mandatory
      LOG_CHANNEL: $LOG_CHANNEL # Not mandatory
      DATABASE_URL: $DATABASE_URL  # defaults to None
      OKTETO_TOKEN: $OKTETO_TOKEN
